### PR TITLE
Slight ergonomic improvements

### PR DESCRIPTION
**Pull request by alexcrichton**
Was reading your post and saw a few possible changes, feel free to pick and choose whatever you'd like!

### CODE REVIEW

**Comment by mgattozzi** [comment]
This is really cool thank you! I'm going to merge this but curious as to why this lets me avoid having to implement `NewService`. Does the closure act with the trait constraints given for `NewService` and then uses that closure as the `new_service` function?

**Comment by alexcrichton** [comment]
Yeah the closure satisfies [this impl](https://github.com/tokio-rs/tokio-service/blob/6c5de5610fb966f59aa7b6b49f2124a4edd9a975/src/lib.rs#L178-L190) where it's just called instead of `NewService::new_service`, so a new instance of the `Webhook` service is created for each connection (by the closure each time)

**Comment by mgattozzi** [comment]
Sweet! That's good to know! Thanks for the improvements. This is some seriously good stuff that you've been working on. I'm seriously impressed

**Comment by alexcrichton** [comment]
Glad you're enjoying it! Don't hesitate to open issues if you encounter any!

**Comment by mgattozzi** [comment]
So far I haven't but I will if I do have any show up!

**Pull request merged**
